name: Upload to S3 Bucket

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install AWS CLI
      run: pip3 install awscli
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_TOKEN }}
        aws-region: us-east-1
    - name: construct URL for our APIgateway
      run : TEMP_URL=`aws apigateway get-rest-apis | python3 -c "import json,sys;
            items=json.load(sys.stdin)['items'];app=next((item for item in items if item['name'] == 'sam-app'), None);id=app['id'];
            url=f'https://{id}.execute-api.us-east-1.amazonaws.com/prod/count';
            print(url);"`
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: '(fetch\(")(.*)(",)'
        replace: $TEMP_URL
        include: "script.js" 
    - name: upload the files to s3
      run: aws s3 cp . s3://${{ secrets.BUCKET_NAME }}/ --recursive  --exclude ".git/*" --exclude ".gitignore"
    - name: Invalidate cloudfront cache
      run: aws cloudfront create-invalidation --distribution-id E1YMUGCIDETE8R --paths "/script.js" "/index.html" "/style.css"